config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: "omniauth_callbacks"
      }
  
  resources :users do
    member do
      get 'add_friend' => 'users#add_friend'
    end
  end
  
  resources :friendables do
    member do
      put 'friend_request'
      put 'friend_request_accept'
      delete 'friend_request_reject'
    end
  end
  
  get 'notification' => 'static_pages#notification'
  
  resources :posts do
    member do
      post 'like' => 'posts#like'
      delete 'unlike' => 'posts#unlike'
    end
  end
  
  resources :comments, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic
  gravtastic
  mount_uploader :image, PictureUploader
  validate :picture_size

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
         
  has_many :posts, foreign_key: :author_id
  has_many :comments
  
  # associations for 'Like' posts
  has_many :user_posts, foreign_key: :liking_user_id
  has_many :liked_posts, through: :user_posts
  
  # associations for friend invites
  has_many :friendables_from, foreign_key: :from_id, class_name: 'Friendable'
  has_many :friendables_to, foreign_key: :to_id, class_name: 'Friendable'
  has_many :inviters, through: :friendables_to, class_name: 'User'
  has_many :invited_users, through: :friendables_from, class_name: 'User'
  
  def friend_request_status(user)
    if Friendable.find_by(from_id: self.id, to_id: user.id, accepted: true) || Friendable.find_by(from_id: user.id, to_id: self.id, accepted: true)
      return 'friends'
    elsif Friendable.find_by(from_id: self.id, to_id: user.id, accepted: false) 
      return 'pending'
    elsif Friendable.find_by(from_id: user.id, to_id: self.id, accepted: false)
      return 'awaiting reply'
    else
      return nil
    end
  end
  
  def friends
    friends = []
    friendables = []
    friendables << Friendable.where(accepted: true).where(to_id: self.id)
    friendables << Friendable.where(accepted: true).where(from_id: self.id)
    friendables.each do |d|
      d.each do |f|
        if f.to_id == self.id
          puts'from_id'
          friends << User.find(f.from_id)
        else
          puts'to_id'
          friends << User.find(f.to_id)
        end
      end
    end
    friends
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
  def picture_size 
    if image.size > 5.megabytes 
      errors.add(:image, "should be less than 5MB") 
    end 
  end 
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
     UserMailer.welcome(@user).deliver_now! if @user.save
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.for(:sign_up) << :name
     devise_parameter_sanitizer.for(:sign_up) << :image
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.for(:account_update) << :name
     devise_parameter_sanitizer.for(:account_update) << :image
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :authenticate_user!
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
        @post = @user.posts.new
        @posts = @user.posts.all.order(created_at: :desc)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/index.html.erb
<% @users.each do |u| %>
<!-- image -->
<div class="container">
<% if u.image.blank? %>
    <%= image_tag u.gravatar_url %>
<% else %>
    <%= image_tag u.image, size: '80' %>
<% end %>
<h2>
<%= link_to u.name, user_path(u) %>
</h2>
<% if current_user.friend_request_status(u) == nil && current_user != u %>
    <%= button_to 'add friend', friend_request_friendable_path(u), method: :put, params: { url: request.original_url }, class: "btn" %>
<% end %> <br>
</div>
<% end %>

app/views/users/show.html.erb
<div class="container" style="width: 60%; text-align: center;">
<% if @user.image.blank? %>
    <%= image_tag @user.gravatar_url %>
<% else %>
    <%= image_tag @user.image %>
<% end %><br>
<strong>Name:</strong> <%= @user.name %> <br>
<strong>E-mail:</strong> <%= @user.email %><br>
<!-- friend request button -->
<% if current_user == @user %>
    <%= link_to 'Edit Profile', edit_user_registration_path(current_user) %>
<% elsif current_user.friend_request_status(@user) == 'friends' %>
    Friend
<% elsif current_user.friend_request_status(@user) == nil %>
    <%= button_to 'add friend', friend_request_friendable_path(@user), method: :put, params: { url: request.original_url }, class: 'btn' %>
<% elsif current_user.friend_request_status(@user) == 'pending' %>
    friend request sent
<% elsif current_user.friend_request_status(@user) == 'awaiting reply' %>
    <%= button_to 'accept friend request', friend_request_accept_friendable_path(@user), method: :put, params: { url: request.original_url }, class: 'btn' %>
    <%= button_to 'reject friend request', friend_request_reject_friendable_path(@user), method: :delete, params: { url: request.original_url }, class: 'btn' %>
<% end %> 
<br>

<!-- new post form -->
<%= render '/posts/form' if current_user == @user%><br>
<br>

<!-- post display & like button -->
<%= render '/posts/post' %>

<strong>Friends:</strong><br>
<% @user.friends.each do |f| %>
<%= link_to f.name, user_path(f) %><br>
<% end %>
</div>