config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: "omniauth_callbacks"
      }
  
  resources :users do
    member do
      get 'add_friend' => 'users#add_friend'
    end
  end
  
  resources :friendables do
    member do
      put 'friend_request'
      put 'friend_request_accept'
      delete 'friend_request_reject'
    end
  end
  
  get 'notification' => 'static_pages#notification'
  
  resources :posts do
    member do
      post 'like' => 'posts#like'
      delete 'unlike' => 'posts#unlike'
    end
  end
  
  resources :comments, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :author, class_name: 'User'
    has_many :comments
    has_many :user_posts, foreign_key: :liked_post_id
    has_many :liking_users, through: :user_posts
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @post = current_user.posts.new
    @posts = Post.where(author_id: current_user.id)
    current_user.friends.each do |f|
     Post.where(author_id: f.id).map{ |d| @posts << d }
    end
    @posts.order(created_at: :desc)
    
  end

  def new
    @user = current_user
    @post = @user.posts.new
  end
  
  def create
    @user = current_user
    @post = @user.posts.build(post_params).save
    redirect_to params[:post][:url]
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.update(post_params)
    redirect_to params[:url]
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end
  
  def like
    if UserPost.find_by(liked_post_id: Post.find(params[:id]), liking_user_id: current_user.id).nil?
      current_user.liked_posts << Post.find(params[:id]) 
      redirect_to params[:url]
    else
      redirect_to params[:url], alert: 'you already liked this post!'
    end
  end
  
  def unlike
    @post = Post.find(params[:id])
    @user_post = UserPost.find_by(liked_post_id: @post, liking_user_id: current_user.id)
    if @user_post
      @user_post.destroy
      redirect_to params[:url]
    else
      redirect_to params[:url], alert: 'you havent liked this post!'
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:content, :picture)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<style>
    .form {
        resize: none;
    }
</style>
<div class="container">
<div class="form">
<%= form_for @post, html: { multipart: true } do |f| %>
<%= f.label :content, 'New post' %><br>
<%= f.text_area :content, size: '40x5', class: 'form' %><br>
<%= f.hidden_field :url, value: request.original_url %>
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'btn' %><br>
<%= f. submit 'post', class: 'btn'%>
<% end %>
</div>
</div>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/_post.html.erb
<style>
    .content {
        font-size: 1.3em;
        font-weight: bold;
    }
</style>

<% @posts.each do |p| %>
    <div class="container">
    <%= image_tag p.picture.url if p.picture? %>
    <div class="content"><%= p.content %></div><br>
     by <%= p.author.name %> at <%= p.created_at.to_s(:long) %><br>
<!-- like button -->
    <%= pluralize(p.liking_users.count, 'like') %>
    <% if UserPost.find_by(liked_post_id: Post.find(p.id), liking_user_id: current_user.id).nil? %>
        <%= button_to 'Like', like_post_path(p), params: {url: request.original_url}, class: 'btn'  %>
    <% else %>
        <%= button_to 'Unlike', unlike_post_path(p), params: {url: request.original_url}, method: :delete, class: 'btn' %>
    <% end %>
    <br>

<!-- comment -->
    <strong>Comment:</strong>
    <div class="comment">
    <% p.comments.each do |c| %>
        <br>
        <div class="comment-item">
            <strong><%= c.content %></strong> by <%= c.user.name %><br>
        </div>
    <% end %>
    <%= form_for :comment, method: :post, url: comments_path do |f| %>
        <%= f.text_field :content %>
        <%= f.hidden_field :url, value: request.original_url %>
        <%= f.hidden_field :post_id, value: p.id %>
        <%= f. submit 'post', class: 'btn'%>
    <% end %>
    </div>
<br>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<%= render 'form' %>
<%= render 'post' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>