config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: "omniauth_callbacks"
      }
  
  resources :users do
    member do
      get 'add_friend' => 'users#add_friend'
    end
  end
  
  resources :friendables do
    member do
      put 'friend_request'
      put 'friend_request_accept'
      delete 'friend_request_reject'
    end
  end
  
  get 'notification' => 'static_pages#notification'
  
  resources :posts do
    member do
      post 'like' => 'posts#like'
      delete 'unlike' => 'posts#unlike'
    end
  end
  
  resources :comments, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<style>
  header {
    background: #004d99;
    padding: 10px 0px;
  }
  th > a {
    text-decoration: none;
    color: white;
    padding-left: 50px;
  }
  th > a:hover {
    text-decoration: none;
    color: white;
    padding-left: 50px;
  }

</style>

<html>
<head>
  <title>OdinFacebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <table>
    <th><%= link_to current_user.email, user_path(current_user) if !current_user.nil? %></th>
    <% if user_signed_in? %>
      <th><%= link_to 'Users', users_path %></th>
      <th><%= link_to 'Posts', posts_path %></th>
      <th><%= link_to 'Notifications', '/notification' %></th>
      <th><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></th>
    <% else %>
      <th><%= link_to 'Home', root_path %></th>
      <th><%= link_to 'Sign Up', new_user_registration_path %></th>
      <th><%= link_to 'Log In', new_user_session_path %></th>
    <% end %>
  </table>
  
</header>
<body>
  <% if !notice.nil? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if !alert.nil? %>
    <p class="alert"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>